### ISSUE TITLE
melpa-stable package

### ISSUE THREAD

**Issue by favadi** [paradoxxxzero/jinja2-mode#13]
The package isn't available in https://stable.melpa.org, this issue is a request to tag and release jinja2-mode in melpa stable.

**Comment by mzuther** [comment]
This should be as simple as

    $ git tag -m "v0.2" v0.2 cfaa7bb
    $ git push --tags origin

Thanks for listening!

Best, Martin

**Comment by paradoxxxzero** [comment]
Whoops totally forgot about this. Is it better now?

**Comment by mzuther** [comment]
Great, it works flawlessly.  Thanks! :)

**Comment by favadi** [comment]
Thanks, it works.
