### ISSUE TITLE
Is there way to disable indenting?

### ISSUE THREAD

**Issue by umeboshi2** [paradoxxxzero/jinja2-mode#16]
I would really like to disable indenting altogether.  Is this possible?

**Comment by sdwolfz** [comment]
As a workaround:

```elisp
  (add-hook 'jinja2-mode-hook
    (lambda ()
      (remove-hook 'after-save-hook 'jinja2-indent-buffer t)))
```

A variable inside this mode to enable this feature, default disabled would be best.

**Comment by grdryn** [comment]
As a new jinja2-mode user, looking for a solution to this issue is what brought me here. Thanks for the workaround @sdwolfz , and hopefully your PR will get merged soon :)
