### ISSUE TITLE
Jinja2 mode should not add indent function to `'after-save-hook` by default

### ISSUE THREAD

**Issue by azenan** [paradoxxxzero/jinja2-mode#18]
The recent commit: https://github.com/paradoxxxzero/jinja2-mode/commit/5ac022d6889a04332b9dbfa390cbb02db3ca57b0

Added a custom function to the `after-save` hooks. This will run the auto-indent function in **all** modes. Which is not ideal. For example, when editing a C file, it will attempt to re-indent the entire file.

Suggest to make this mode an option, not the default.

**Comment by charlesd-tm** [comment]
I agree.  It is completely destroying my Ansible YAML files when I try to save them.

**Comment by daviderestivo** [comment]
I have just created a PR https://github.com/paradoxxxzero/jinja2-mode/pull/19 that should solve this issue.

**Comment by chenzaichun** [comment]
PR #17 makes emacs hang in org-mode while saving if jinjia2 included.

**Comment by opsaaspo** [comment]
`PR #17 makes emacs hang in org-mode while saving if jinjia2 included`
I've spent a lot of time for find it ;(.

**Comment by idcrook** [comment]
I spent two days across multiple machines and operating systems to finally figure out why my yaml and  python files were getting reformatted (incorrectly, and so breaking, since indentation is scope) before I just figured this out this morning (this issue)... 

unfortunately google was no help, and since it was first appearing in machines where emacs-snapshot was installed (and had the breaking change installed globally into `'after-save-hook`) I was debugging what I thought might be a bug with emacs itself. anyway, adding this message for search engine cookie crumbs

**Comment by idcrook** [comment]
I figured I'd suggest another way to add another layer of safety to a format hook itself. Check buffer type before running. example copied from `go-mode.el`

```lisp
;;;###autoload
(defun gofmt-before-save ()
  "Add this to .emacs to run gofmt on the current buffer when saving:
\(add-hook 'before-save-hook 'gofmt-before-save).

Note that this will cause ‘go-mode’ to get loaded the first time
you save any file, kind of defeating the point of autoloading."

  (interactive)
  (when (eq major-mode 'go-mode) (gofmt)))

```

I think the local variable option works along side this approach.

**Comment by corrafig** [comment]
@idcrook I had similar experience. However, now I'm happy because now I know more Emacs and how to debug it. :)

**Comment by daviderestivo** [comment]
> I think the local variable option works along side this approach.

Yup, the result should be the same.

**Comment by daviderestivo** [comment]
@paradoxxxzero thanks for having merged https://github.com/paradoxxxzero/jinja2-mode/pull/19. I have tested it and the issue seem to be fixed. I guess we can close this ticket.

**Comment by paradoxxxzero** [comment]
No problem, sorry for the bad merge

**Comment by mzuther** [comment]
I'm not sure whether I should open a new issue. But it would have *exactly* the same title, so I chose to comment here instead.

My problem is that you add a hook for indenting the buffer which I cannot (easily) get rid of. But I have tediously crafted my Jinja2 templates and do *not* want any automatic indentation to happen.

Would it be possible to add a configuration option to make automatic indentation optional? I'd also recommend to disable automatic indentation by default - this is something that users do not expect, so it's best to "catch them where they are".

Thanks a lot (which includes creating jinja2-mode in the first place)!

**Comment by daviderestivo** [comment]
> Would it be possible to add a configuration option to make automatic indentation optional? I'd also recommend to disable automatic indentation by default - this is something that users do not expect, so it's best to "catch them where they are".

I think this should be quite easy. @paradoxxxzero If you like I can prepare a PR with this change :)
